version: '3.3'
services:

  template-terraform-apply:
    image: sebczu/personal:template-terraform-0.0.1
    container_name: template-terraform-apply
    command:
      - apply -auto-approve
    environment:
      - CREDENTIAL_GCLOUD=${CREDENTIAL_GCLOUD}
      - CREDENTIAL_DOCKERHUB=${CREDENTIAL_DOCKERHUB}
      - CREDENTIAL_GITHUB=${CREDENTIAL_GITHUB}
      - CREDENTIAL_GCLOUD_SQL=${CREDENTIAL_GCLOUD_SQL}