version: '3.3'
services:

  template-terraform-apply:
    image: template-terraform:0.0.1
    container_name: template-terraform
    environment:
      - CREDENTIAL=${CREDENTIAL}
      - TYPE=APPLY
    volumes:
      - ./volumes/terraform.tfstate:/scripts/terraform.tfstate