name: Apply

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Terraform command'
        default: 'apply -auto-approve'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Run terraform command
        run: |
          echo "Command ${{ github.event.inputs.name }}"
          cat docker/volumes/terraform.tfstate