name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build docker image
      run: >
        docker build -t sebczu/personal:template-terraform-0.0.1 service
    - name: Push docker image
      run: >
        docker images
