name: Terraform command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Terraform command'
        default: 'apply -auto-approve'
        required: true

jobs:
  terraform_command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run terraform command
        run: |
          echo "Command ${{ github.event.inputs.command }}"
          docker run \
            -e "CREDENTIAL_GCLOUD=${{ secrets.CREDENTIAL_GCLOUD }}" \
            -e "CREDENTIAL_DOCKERHUB=${{ secrets.CREDENTIAL_DOCKERHUB }}" \
            -e "CREDENTIAL_GITHUB=${{ secrets.CREDENTIAL_GITHUB }}" \
            sebczu/personal:template-terraform-0.0.1 \
            "${{ github.event.inputs.command }}"
